name: dart_wot
description: A W3C Web of Things implementation written in Dart. Supports interacting with Things using CoAP(S) and HTTP(S).
version: 0.19.1
homepage: https://github.com/namib-project/dart_wot

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.4
  dart_code_metrics: ^4.7.0
  lint: ^1.8.2
  lints: ^1.0.0
  mockito: ^5.0.17
  test: ^1.16.0

dependencies:
  cbor: ^5.0.0
  coap: ^4.0.0
  collection: ^1.16.0
  curie: ^0.1.0
  http: ^0.13.4
  http_auth: ^1.0.1
  http_parser: ^4.0.0
  json_schema3: ^1.0.0
  meta: ^1.8.0
  typed_data: ^1.3.0
  uri: ^1.0.0
  uuid: ^3.0.5
