name: dart_wot
description: A W3C Web of Things implementation written in Dart. Supports interacting with Things using CoAP(S) and HTTP(S).
version: 0.15.0
homepage: https://github.com/namib-project/dart_wot

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  coverage: ^1.0.4
  lints: ^1.0.0
  test: ^1.16.0
  dart_code_metrics: ^4.7.0
  build_runner: ^2.1.7
  mockito: ^5.0.17

dependencies:
  coap: ^4.0.0
  cbor: ^5.0.0
  http: ^0.13.4
  http_auth: ^1.0.1
  http_parser: ^4.0.0
  json_schema2: ^2.0.1+2
  typed_data: ^1.3.0
  uri: ^1.0.0
  uuid: ^3.0.5
  curie: ^0.1.0
