name: dart_wot
description: A W3C Web of Things implementation written in Dart. Supports interacting with Things using CoAP, HTTP, and MQTT.
version: 0.37.1
homepage: https://github.com/eclipse-thingweb/dart_wot

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  coverage: ^1.0.4
  lint: ^2.0.2
  lints: ^4.0.0
  mockito: ^5.0.17
  test: ^1.24.3

dependencies:
  cbor: ^6.1.0
  coap: ^9.1.0
  collection: ^1.17.2
  curie: ^0.1.0
  dcaf: ^0.1.0
  http: ^1.0.0
  http_auth: ^1.0.2
  http_parser: ^4.0.0
  json_schema: ^5.1.2
  meta: ^1.8.0
  mqtt_client: ^10.0.0
  multicast_dns: ^0.3.2+1
  sse_channel: ^0.1.1
  typed_data: ^1.3.2
  uri: ^1.0.0
  uuid: ^4.2.1
