name: dart_wot
description: A W3C Web of Things implementation written in Dart. Supports interacting with Things using CoAP and HTTP(S).
version: 0.9.0
homepage: https://github.com/namib-project/dart_wot

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  coverage: ^1.0.4
  lints: ^1.0.0
  test: ^1.16.0
  dart_code_metrics: ^4.7.0

dependencies:
  cbor: ^4.1.0
  coap: ^3.4.0
  http: ^0.13.4
  http_auth: ^1.0.1
  http_parser: ^4.0.0
  typed_data: ^1.3.0
  uuid: ^3.0.5
